[template]
  incoming-hooks = ["Sanity"]

[template.environment]
  NEXT_PUBLIC_SANITY_PROJECT_ID="rmr3399o"
  NEXT_PUBLIC_SANITY_DATASET="production"
  SANITY_API_WRITE_TOKEN="skFPvYbQLnUL0mkfAGWgihvBYVYxSmBLVIUQdBRA5Qk71sO0cZqskxFYXwppcGzv628uZjnvHXo14GHxK3AQSsdWyfTmceQErFEthMcfbVHaBcQLKoGlOzlAMO0G3B5QcTRcYNCc54TqovS8TelEKcWpgrpMlpvAPRUwpQa1f3986pW8bkY2"
  SANITY_API_READ_TOKEN="skFPvYbQLnUL0mkfAGWgihvBYVYxSmBLVIUQdBRA5Qk71sO0cZqskxFYXwppcGzv628uZjnvHXo14GHxK3AQSsdWyfTmceQErFEthMcfbVHaBcQLKoGlOzlAMO0G3B5QcTRcYNCc54TqovS8TelEKcWpgrpMlpvAPRUwpQa1f3986pW8bkY2"